### PR TITLE
Added Gestures

### PR DESCRIPTION
**Pull request by enwokoma**
Added feature to swipe and change songs on left or right swipe gesture

### CODE REVIEW

**Comment by enwokoma** [comment]
I don't know why Codacy is flagging the commits as **Not up to standards**
Everything works fine and should be able to merge anyways 🤷‍♂️

**Comment by enwokoma** [comment]
This is a very important feature. So, I would mark this as ready for review now and you can merge accordingly.

**Comment by enwokoma** [comment]
Boom!
All good to go now.

**Comment by Charlieras262** [comment]
Hi!
Thanks @enwokoma for your contribution.

**Pull request merged**
